baseURL: https://www.dydxdz.xyz/
languageCode: cn-zh
title: xiaoshu.ai
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/xiaoshuai.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Learn Programming
    # Hero subtitle (optional)
    subtitle: 又一个简单的在线编程学习网站
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
  navbar:
  - title: 专栏
    sublinks:
    - title: CS101计算机科学基础
      url: /zhuanlan/cs101/
    - title: Python编程
      url: /zhuanlan/python/
    - title: HTML/CSS/JavaScript
      url: /zhuanlan/javascript/
    - title: Linux与Shell
      url: /zhuanlan/linux-and-shell/
    - title: Docker与Kubernetes
      url: /zhuanlan/docker-and-kubernetes/
    - title: TCP/IP协议
      url: /zhuanlan/tcp-ip/
    - title: 云计算技术
      url: /zhuanlan/cloud-computing/
  - title: Playground
    sublinks:
    - title: 在线写Python
      url: https://play.xiaoshu.ai/
    - title: Python Shell
      url: https://play.xiaoshu.ai/python-shell/
    - title: 在线玩Linux操作系统
      url: https://play.xiaoshu.ai/linux/
    - title: 在线学Git
      url: https://play.xiaoshu.ai/learn-git-branching/
    - title: 儿童编程Scratch
      url: https://play.xiaoshu.ai/scratch/
  - title: Blog
    url: /
  - title: 关于
    sublinks:
    - title: 我是谁
      link: /
    - title: 如何选择
      link: /
    - title: 关于实验室
      link: /
  - title: 进入实验室Lab
    url: https://lab.xiaoshu.ai/
    button: true
  sidebar:
  section1: false
  section2: false
  section3: false
  section4: false
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: 关注我
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/xiaoshu-ai
      icon: github
    - link: https://github.com/xiaoshu-ai
      icon: git
    - link: https://www.douyin.com/user/MS4wLjABAAAAhBeHtoLlBbSPWyeBXLEI5n4Q2tpuo0FOQSyhEnNOnKdkR5RxoAyasqJP2dW2iVJT
      icon: tiktok
    - link: /
      icon: weixin
    - link: https://space.bilibili.com/1013505916
      icon: bilibili
    - link: https://www.zhihu.com/people/xiaoshu.ai
      icon: zhihu
    bulmalogo: true
    quicklinks:
      column1:
        title: 专栏
        links:
        - text: CS101计算机科学基础
          link: /zhuanlan/cs101/
        - text: Python编程
          link: /zhuanlan/python/
        - text: HTML/CSS/JavaScript
          link: /zhuanlan/javascript/
        - text: Linux与Shell
          link: /zhuanlan/linux-and-shell/
        - text: Docker/Kubernetes
          link: /zhuanlan/docker-and-kubernetes/
        - text: TCP/IP协议
          link: /zhuanlan/tcp-ip/
      column2:
        title: 关于
        links:
        - text: 我是谁
          link: /
        - text: 如何选择
          link: /
        - text: 关于实验室
          link: /
